namespace: url-monitor

image:
  repository: dimitartsvetkov/infra-task1
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

serviceAccount:
  create: true
  name: ""
  annotations: {}

ingress:
  enabled: false
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
